name: Move Issue to Done

on:
  issue_comment:
    types: [created]

jobs:
  move-to-done:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the comment contains 'done'
        if: contains(github.event.comment.body, 'done')
        run: echo "Comment contains 'done', processing the issue..."

      - name: Move Issue to 'Done'
        if: contains(github.event.comment.body, 'done')
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: move-to-done
