name: Move Issue to Done

on:
  issue_comment:
    types: [created]

jobs:
  move-to-done:
    runs-on: ubuntu-latest

    steps:
      # Step to set the GH_TOKEN and fetch the issue ID from GitHub GraphQL API
      - name: Set GH_TOKEN environment variable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Query GitHub GraphQL API for the issue's ID
          ISSUE_ID=$(gh api graphql -f query='
          {
            repository(owner: "Aishwarya187423", name: "Aishwarya-Zelda-Game") {
              issue(number: ${{ github.event.issue.number }}) {
                id
              }
            }
          }' --jq '.data.repository.issue.id')
          
          # Set the issue ID as an environment variable
          echo "ISSUE_ID=${ISSUE_ID}" >> $GITHUB_ENV

      # Log the issue comment details
      - name: Log the issue comment details
        run: |
          echo "Debug: Comment body: ${{ github.event.comment.body }}"
          echo "Debug: Comment author: ${{ github.event.comment.user.login }}"
          echo "Debug: Issue number: ${{ github.event.issue.number }}"
          echo "Debug: Issue ID: ${{ env.ISSUE_ID }}"

      # Step to check if the comment contains 'done'
      - name: Check if the comment contains 'done'
        if: contains(github.event.comment.body, 'done')
        run: echo "Comment contains 'done', proceeding to move the issue..."

      # Move the issue to 'Done' status using the automation tool
      - name: Move Issue to 'Done'
        if: contains(github.event.comment.body, 'done')
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          user: "Aishwarya187423"
          resource_node_id: ${{ env.ISSUE_ID }}  # Use the dynamically set issue ID
          move_related_issues: true
          PROJECT_ID : 6
          status_value: "Done"
          operation_mode: status

      # Log success after moving the issue
      - name: Log success
        if: contains(github.event.comment.body, 'done')
        run: echo "Successfully moved the issue to 'Done' status."
