name: Move Issue to Done

on:
  issue_comment:
    types: [created]

jobs:
  move-to-done:
    runs-on: ubuntu-latest

    steps:
      - name: Set GH_TOKEN environment variable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NODE_ID=$(gh api graphql -f query='
          {
            repository(owner: "YOUR_USERNAME", name: "YOUR_REPOSITORY_NAME") {
              issue(number: ${{ github.event.issue.number }}) {
                node_id
              }
            }
          }' --jq '.data.repository.issue.node_id')
          echo "NODE_ID=${NODE_ID}" >> $GITHUB_ENV

      # Log the issue comment details
      - name: Log the issue comment details
        run: |
          echo "Debug: Comment body: ${{ github.event.comment.body }}"
          echo "Debug: Comment author: ${{ github.event.comment.user.login }}"
          echo "Debug: Issue number: ${{ github.event.issue.number }}"
          echo "Debug: Issue node ID: ${{ github.event.issue.node_id }}"

      # Check if the comment contains 'done'
      - name: Check if the comment contains 'done'
        if: contains(github.event.comment.body, 'done')
        run: echo "Comment contains 'done', proceeding to move the issue..."

      # Move the issue to 'Done'
      - name: Move Issue to 'Done'
        if: contains(github.event.comment.body, 'done')
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          project_id: "PVT_kwHOCtxenM4As1ms"  # Replace this with your project ID
          user: "@me"
          resource_node_id: ${{ env.NODE_ID }}  # Use the dynamically set value
          move_related_issues: true
          status_value: "Done"
          operation_mode: status

      # Log success after moving the issue
      - name: Log success
        if: contains(github.event.comment.body, 'done')
        run: echo "Successfully moved the issue to 'Done' status."
