name: Move Issue to Done

on:
  issue_comment:
    types: [created]

jobs:
  move-to-done:
    runs-on: ubuntu-latest

    steps:
      - name: Log the issue comment details
        run: |
          run: echo "Debug: Issue Node ID is: ${{ github.event.issue.node_id }}"
          echo "Debug: Comment body is: ${{ github.event.comment.body }}"
          echo "Debug: Comment author is: ${{ github.event.comment.user.login }}"
          echo "Debug: Issue number is: ${{ github.event.issue.number }}"

      - name: Set the NODE_ID environment variable
        run: echo "NODE_ID=${{ github.event.issue.node_id }}" >> $GITHUB_ENV

      - name: Check if the comment contains 'done'
        if: contains(github.event.comment.body, 'done')
        run: echo "Comment contains 'done', proceeding to move the issue..."

      - name: Move Issue to 'Done'
        if: ${{ github.event.comment.body && contains(github.event.comment.body, 'done') }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          project_id: "PVT_kwHOCtxenM4As1ms" # Replace this with your project ID
          user: "@me"
          resource_node_id: ${{ env.NODE_ID }}
          move_related_issues: true
          status_value: "Done"
          operation_mode: status

      - name: Log success
        if: ${{ github.event.comment.body && contains(github.event.comment.body, 'done') }}
        run: echo "Successfully moved the issue to 'Done' status."
