name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Clear npm cache to avoid conflicts
    - name: Clear npm cache
      run: npm cache clean --force

    # Step 4: Install dependencies
    - name: Install Dependencies
      run: npm ci

    # Step 5: Run Jest Tests
    - name: Run Jest Tests
      run: npm test
