name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: List directory contents (for debugging purposes)
    - name: List directory contents
      run: ls -R

    # Step 4: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 5: Run tests
    - name: Run Jest Tests
      run: npm test
