name: Auto-Label Issues

on:
  issues:
    types: [opened] # Trigger the workflow when a new issue is created

jobs:
  auto-label:
    runs-on: ubuntu-latest # Run on the latest Ubuntu environment

    steps:
      - name: Auto-label based on issue description
        uses: actions/github-script@v6 # Use the GitHub Script action
        with:
          script: |
            // Get the issue description and convert it to lowercase
            const issueBody = context.payload.issue.body?.toLowerCase() || "";

            // Define the keywords and their corresponding labels
            const keywordsToLabels = {
              bug: 'bug',
              enhancement: 'enhancement',
              documentation: 'documentation',
              duplicate: 'duplicate',
              good_first_issue: 'good first issue',
              help_wanted: 'help wanted',
              invalid: 'invalid',
              wontfix: 'wontfix',
            };

            // Array to hold labels to add
            const labelsToAdd = [];

            // Check for each keyword in the issue body and add the corresponding label
            Object.keys(keywordsToLabels).forEach((keyword) => {
              if (issueBody.includes(keyword)) {
                labelsToAdd.push(keywordsToLabels[keyword]);
              }
            });

            // Apply the labels if any match
            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner, // Repo owner
                repo: context.repo.repo,   // Repo name
                issue_number: context.payload.issue.number, // Issue number
                labels: labelsToAdd, // Labels to apply
              });

              console.log(`Labels added: ${labelsToAdd.join(', ')}`);
            } else {
              console.log("No matching labels found in the issue description.");
            }
